// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Contexts;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20260802043013_RemoveDerivedFromRegionTier")]
    partial class RemoveDerivedFromRegionTier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.BoostTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Boost")
                        .HasColumnType("int");

                    b.Property<int>("MinParcels")
                        .HasColumnType("int");

                    b.Property<decimal>("NoAdsMonth")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("ParcelsLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("RegionTierId")
                        .HasColumnType("int");

                    b.Property<decimal>("SrbYear")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("WithAdsMonth")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("WithAdsYear")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("RegionTierId");

                    b.ToTable("BoostTier", (string)null);
                });

            modelBuilder.Entity("api.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FaqGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FaqGroupId");

                    b.ToTable("FAQ", (string)null);
                });

            modelBuilder.Entity("api.Models.FAQGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FAQGroup", (string)null);
                });

            modelBuilder.Entity("api.Models.Glossary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Glossary", (string)null);
                });

            modelBuilder.Entity("api.Models.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Odds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 12)
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.ToTable("Parcel", (string)null);
                });

            modelBuilder.Entity("api.Models.RegionCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("RegionTierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionTierId");

                    b.ToTable("RegionCountry", (string)null);
                });

            modelBuilder.Entity("api.Models.RegionTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("RegionTier", (string)null);
                });

            modelBuilder.Entity("api.Models.BoostTier", b =>
                {
                    b.HasOne("api.Models.RegionTier", "RegionTier")
                        .WithMany("Tiers")
                        .HasForeignKey("RegionTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegionTier");
                });

            modelBuilder.Entity("api.Models.FAQ", b =>
                {
                    b.HasOne("api.Models.FAQGroup", "FaqGroup")
                        .WithMany("Questions")
                        .HasForeignKey("FaqGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaqGroup");
                });

            modelBuilder.Entity("api.Models.RegionCountry", b =>
                {
                    b.HasOne("api.Models.RegionTier", "RegionTier")
                        .WithMany("Countries")
                        .HasForeignKey("RegionTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegionTier");
                });

            modelBuilder.Entity("api.Models.FAQGroup", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("api.Models.RegionTier", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
