export const faqData = [
  {
    category: "Getting Started",
    questions: [
      {
        q: "What is Atlas Earth?",
        a: "Atlas Earth is a mobile game where you buy virtual plots of real-world land (parcels) mapped to the real globe. Each parcel you own generates virtual rent every second, which can eventually be cashed out for real money."
      },
      {
        q: "Is Atlas Earth free to play?",
        a: "Yes, 100%. While you can spend real money to buy in-game currency, you can play entirely for free by collecting diamonds on the map, spinning the daily wheel, and watching ads for free Atlas Bucks."
      },
      {
        q: "How do I download Atlas Earth?",
        a: "Atlas Earth is available on both the Apple App Store for iOS devices and the Google Play Store for Android devices."
      },
      {
        q: "What is a parcel?",
        a: "A parcel is a 30ft x 30ft square of virtual land that corresponds to a real-world location. When you buy a parcel, you own that specific piece of the Atlas Earth map."
      },
      {
        q: "What are Atlas Bucks?",
        a: "Atlas Bucks (AB) are the primary in-game currency used to purchase parcels of land and badges. 100 AB buys 1 parcel of land."
      },
      {
        q: "How do I earn Atlas Bucks?",
        a: "You can earn AB by: watching an ad every 20 minutes (for 2 AB), spinning the diamond wheel, connecting a credit card for merchant rewards, converting your earned rent, or buying them with real money."
      }
    ]
  },
  {
    category: "Buying & Owning Land",
    questions: [
      {
        q: "How do I buy a parcel?",
        a: "Open the app, go to the map screen, tap 'Buy Land', and select any available green square around your current physical location. You must be physically near a parcel to buy it."
      },
      {
        q: "What does it cost to buy a parcel?",
        a: "Every parcel costs exactly 100 Atlas Bucks, regardless of its location or rarity."
      },
      {
        q: "Can I buy parcels anywhere in the world?",
        a: "You can only buy parcels within your immediate physical vicinity. You have to travel to a location to buy land there."
      },
      {
        q: "What happens if someone already owns a parcel I want?",
        a: "If a parcel is red on the map, it is owned by someone else. You cannot buy it unless they explicitly list it for sale."
      },
      {
        q: "How many parcels can I own?",
        a: "There is no limit to how many parcels you can own, though your rent boost multiplier will decrease as you hit certain parcel count milestones."
      },
      {
        q: "Can I sell my parcels?",
        a: "Yes, you can list your parcels for sale to other players for a minimum of 150 Atlas Bucks. Atlas Reality takes a 20% cut of the sale."
      }
    ]
  },
  {
    category: "Earnings & Payouts",
    questions: [
      {
        q: "How much can I realistically earn?",
        a: "Earnings are slow. A free-to-play player who stays boosted consistently might make $150-$200 in their first year. It is not a way to get rich or replace a job; treat it as a game that occasionally buys you a coffee."
      },
      {
        q: "How do payouts work?",
        a: "Once you reach the minimum threshold, you can cash out your accrued virtual rent via PayPal, various gift cards, or bank transfer (depending on your region)."
      },
      {
        q: "What is the minimum payout threshold?",
        a: "The minimum amount you can cash out is $5.00 USD."
      },
      {
        q: "How long does it take to get a payout?",
        a: "Most payouts are processed almost instantly, though bank transfers or PayPal can sometimes take up to 48 hours to clear."
      },
      {
        q: "Are earnings taxable?",
        a: "If you cash out more than $600 USD in a calendar year, Atlas Reality requires you to fill out a W-9 tax form (in the US). Consult a tax professional regarding your specific situation."
      }
    ]
  },
  {
    category: "Game Mechanics",
    questions: [
      {
        q: "What are Atlas Coins vs Atlas Bucks?",
        a: "Atlas Bucks (AB) are used to buy land and badges. Atlas Coins are the currency representing your accrued rent (the micro-fractions of a cent generated by your land) which converts directly to real USD."
      },
      {
        q: "Is there a referral program?",
        a: "Atlas Reality sunset their referral program at the end of January 2026. It is no longer active. There is no longer a way to earn passive income by referring other players."
      },
      {
        q: "What are badges and how do I earn them?",
        a: "Badges are collectibles for specific cities, states, and countries. Buying a badge costs 200 AB and provides a permanent percentage boost to your overall rent generation across all your parcels."
      },
      {
        q: "What is rent and how is it calculated?",
        a: "Rent is generated every second based on the rarities of your parcels. Common = $0.0000000011/sec, Rare = $0.0000000016/sec, Epic = $0.0000000022/sec, Legendary = $0.0000000044/sec. This is multiplied by your ad boost and badge boosts."
      },
      {
        q: "Do parcels in cities earn more than rural parcels?",
        a: "No. The location of a parcel has absolutely no effect on its rarity or rent generation. A parcel in Times Square has the exact same odds of being Legendary as a parcel in an empty field."
      },
      {
        q: "What are Atlas Landmarks?",
        a: "Landmarks are special, recognizable real-world locations (like the Statue of Liberty). Currently, they cannot be purchased, though future updates plan to add gameplay mechanics around them."
      }
    ]
  },
  {
    category: "Tips & Strategy",
    questions: [
      {
        q: "What's the best strategy for new players?",
        a: "Save your first 100 AB and buy your first parcel. Watch ads to keep your rent boosted 24/7. Watch the ad for 2 AB every 20 minutes as often as possible. Do not buy badges until you have about 40 parcels."
      },
      {
        q: "Should I focus on buying lots of cheap parcels or fewer premium ones?",
        a: "You don't get to choose parcel rarity—it's randomly generated when you buy it. The strategy is simply to buy as many parcels as possible and let the odds (50% Common, 30% Rare, 15% Epic, 5% Legendary) play out."
      },
      {
        q: "How do I find the best parcels to buy?",
        a: "Because rarity is entirely random and determined at the moment of purchase, there is no way to 'find' better parcels. It's pure luck."
      },
      {
        q: "Is it worth using real money to buy Atlas Bucks?",
        a: "Generally, no. The Return on Investment (ROI) for buying AB with real money takes years. The best way to play is free-to-play, or by signing up for the Explorer Club if you are a dedicated player."
      },
      {
        q: "What are the most common mistakes new players make?",
        a: "1. Buying badges too early (before 40 parcels). 2. Forgetting to keep their ad boost active. 3. Crossing a tier threshold (e.g., buying parcel #151) which drops their boost multiplier without having enough parcels saved up to jump deep into the next tier."
      }
    ]
  },
  {
    category: "Community & Other",
    questions: [
      {
        q: "Where can I find the Atlas Earth community?",
        a: "The most active community is on Reddit at r/AtlasEarthOfficial. There are also several large Facebook groups dedicated to players sharing strategies."
      },
      {
        q: "Is there an official Discord?",
        a: "While there is no fully official Discord, there are several large, community-run Discord servers linked often in the subreddit."
      },
      {
        q: "How do I report a bug or contact support?",
        a: "You can contact support directly through the settings menu in the app, or via the Atlas Reality website's help center."
      },
      {
        q: "Is Atlas Earth a scam?",
        a: "No. It is a legitimate game that actually pays out. However, you should not view it as an investment or a source of income. It is an ad-revenue sharing app gamified as virtual real estate."
      },
      {
        q: "Can I play Atlas Earth on a desktop/PC?",
        a: "Atlas Earth is a mobile-only application that relies on GPS data. While some players try to use emulators, this risks account bans. You can access the web app to view the map and buy badges/AB, but not to buy parcels or play."
      }
    ]
  }
];

export const glossaryTerms = [
  {
    term: "AB (Atlas Bucks)",
    definition: "The primary in-game currency used to buy parcels of land and badges. Can be bought with real money or earned for free."
  },
  {
    term: "Ad Boost",
    definition: "A multiplier applied to your rent generation. By watching an ad, you boost your rent by a multiplier (up to 30x) for 1 hour. You can stack up to 6 hours at a time."
  },
  {
    term: "Badge",
    definition: "A collectible representing a city, state, or country. Costing 200 AB, they provide permanent percentage-based boosts (5%, 10%, 15%, etc.) to your total rent."
  },
  {
    term: "Diamonds",
    definition: "Collectibles found on the map by physically walking near them. Used exclusively to spin the Diamond Wheel for prizes."
  },
  {
    term: "Diamond Wheel",
    definition: "A daily roulette wheel where you spend diamonds for a chance to win Atlas Bucks. You get 5 spins per day (3 free, 2 requiring ads)."
  },
  {
    term: "Explorer Club",
    definition: "A monthly subscription service ($50/month) that provides a large amount of Atlas Bucks daily just for logging in. Requires you to own 5 badges to join."
  },
  {
    term: "Landmark",
    definition: "Special visual representations of famous real-world locations on the map. Currently aesthetic only."
  },
  {
    term: "Mayor/Governor/President",
    definition: "Titles granted to the player who owns the most parcels in a specific city (Mayor), state (Governor), or country (President). Title holders get a small cut of AB when players buy badges in their territory."
  },
  {
    term: "Parcel",
    definition: "A 30x30 foot plot of virtual land. Costs 100 AB. Generates rent."
  },
  {
    term: "Rarity",
    definition: "Parcels come in 4 tiers: Common (50% chance), Rare (30%), Epic (15%), and Legendary (5%). Higher rarities generate more rent per second."
  },
  {
    term: "Rent",
    definition: "The actual USD value generated by your parcels. Shown as micro-fractions of a cent that accrue constantly."
  },
  {
    term: "SRB (Super Rent Boost)",
    definition: "A special event hosted by Atlas Reality (usually twice a month) where ALL players, regardless of how many parcels they own, get a 50x multiplier on their rent for 32 hours."
  },
  {
    term: "Tier/Tier Drop",
    definition: "As you buy more parcels, your ad boost multiplier decreases to balance the economy (e.g., dropping from 30x to 20x at 151 parcels). The point where this drops is a 'tier'."
  }
];
